-- ============================================================
-- 001_init_schema.sql
-- Inisialisasi Skema Database SIM-HUMAS PUPR Papua Barat Daya
-- ============================================================

-- Enable pgcrypto extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── 1. PROFILES (Extends Supabase Auth users) ───────────────
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'Editor'::text,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by authenticated users." 
  ON public.profiles FOR SELECT 
  TO authenticated USING (true);

CREATE POLICY "Users can insert their own profile." 
  ON public.profiles FOR INSERT 
  TO authenticated WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." 
  ON public.profiles FOR UPDATE 
  TO authenticated USING (auth.uid() = id);


-- ── 2. BERITA ───────────────────────────────────────────────
CREATE TABLE public.berita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  isi TEXT NOT NULL,
  kategori TEXT NOT NULL,
  status TEXT DEFAULT 'draft'::text, -- draft, review, published
  tanggal DATE DEFAULT CURRENT_DATE,
  penulis TEXT,
  views INT DEFAULT 0,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.berita ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Berita is viewable by authenticated users" 
  ON public.berita FOR SELECT TO authenticated USING (true);

CREATE POLICY "Berita can be inserted by authenticated users" 
  ON public.berita FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Berita can be updated by authenticated users" 
  ON public.berita FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Berita can be deleted by authenticated users" 
  ON public.berita FOR DELETE TO authenticated USING (true);


-- ── 3. GALERI MEDIA ─────────────────────────────────────────
CREATE TABLE public.galeri_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT NOT NULL, -- foto, video
  caption TEXT,
  uploaded_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.galeri_media ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Galeri is viewable by authenticated users" 
  ON public.galeri_media FOR SELECT TO authenticated USING (true);

CREATE POLICY "Galeri can be inserted by authenticated users" 
  ON public.galeri_media FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Galeri can be deleted by authenticated users" 
  ON public.galeri_media FOR DELETE TO authenticated USING (true);


-- ── 4. AGENDA ───────────────────────────────────────────────
CREATE TABLE public.agenda (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  tanggal DATE NOT NULL,
  waktu TEXT,
  lokasi TEXT,
  keterangan TEXT,
  warna TEXT DEFAULT 'var(--green)'::text,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.agenda ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Agenda viewable by authenticated users" ON public.agenda FOR SELECT TO authenticated USING (true);
CREATE POLICY "Agenda insertable by authenticated users" ON public.agenda FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Agenda updatable by authenticated users" ON public.agenda FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Agenda deletable by authenticated users" ON public.agenda FOR DELETE TO authenticated USING (true);


-- ── 5. PUBLIKASI ────────────────────────────────────────────
CREATE TABLE public.publikasi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  judul TEXT NOT NULL,
  icon TEXT DEFAULT '📄'::text,
  tanggal DATE,
  tipe TEXT,
  tags TEXT[],
  file_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.publikasi ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Publikasi viewable by authenticated users" ON public.publikasi FOR SELECT TO authenticated USING (true);
CREATE POLICY "Publikasi insertable by authenticated users" ON public.publikasi FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Publikasi updatable by authenticated users" ON public.publikasi FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Publikasi deletable by authenticated users" ON public.publikasi FOR DELETE TO authenticated USING (true);


-- ── 6. MONITORING ───────────────────────────────────────────
CREATE TABLE public.monitoring (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  berita_id BIGINT REFERENCES public.berita(id) ON DELETE CASCADE,
  judul TEXT NOT NULL,
  penulis TEXT NOT NULL,
  tahap TEXT DEFAULT 'draft'::text, -- draft, review, approval, published
  reviewer TEXT,
  deadline TEXT,
  catatan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.monitoring ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Monitoring viewable by authenticated users" ON public.monitoring FOR SELECT TO authenticated USING (true);
CREATE POLICY "Monitoring insertable by authenticated users" ON public.monitoring FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Monitoring updatable by authenticated users" ON public.monitoring FOR UPDATE TO authenticated USING (true);


-- ── 7. AI HISTORY ───────────────────────────────────────────
CREATE TABLE public.ai_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prompt TEXT NOT NULL,
  hasil TEXT,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.ai_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "AI History viewable by authenticated users" ON public.ai_history FOR SELECT TO authenticated USING (true);
CREATE POLICY "AI History insertable by authenticated users" ON public.ai_history FOR INSERT TO authenticated WITH CHECK (true);


-- ── FUNCTIONS & TRIGGERS ────────────────────────────────────

-- Increment Views Function
CREATE OR REPLACE FUNCTION public.increment_views(berita_id BIGINT)
RETURNS void
LANGUAGE sql
AS $$
  UPDATE public.berita
  SET views = views + 1
  WHERE id = berita_id;
$$;

-- Trigger to auto create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Trigger to auto insert into monitoring when berita is created
CREATE OR REPLACE FUNCTION public.handle_new_berita() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.monitoring (berita_id, judul, penulis, tahap)
  VALUES (new.id, new.judul, new.penulis, new.status);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_berita_created
  AFTER INSERT ON public.berita
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_berita();
